name: Convert publish Markdown to PDF

on:
  push:
    paths:
      - '**/publish/**.md'
      - '.github/workflows/convert_publish_markdown_to_pdf.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Pandoc and LaTeX packages
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex texlive-fonts-recommended texlive-latex-extra

      - name: Replace Unicode subscripts with LaTeX
        run: |
          find publish -path '*/docs/*.md' -type f -print0 |
          while IFS= read -r -d '' file; do
            sed -i -E 's/₀/$_0$/g; s/₁/$_1$/g; s/₂/$_2$/g; s/₃/$_3$/g; s/₄/$_4$/g; s/₅/$_5$/g; s/₆/$_6$/g; s/₇/$_7$/g; s/₈/$_8$/g; s/₉/$_9$/g' "$file"
          done

      - name: Convert Markdown files to PDF
        run: |
          find publish -path '*/docs/*.md' -type f -print0 |
          while IFS= read -r -d '' file; do
            pandoc "$file" -o "${file%.md}.pdf" --pdf-engine=xelatex
          done

      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: publish-pdfs
          path: publish/**/docs/*.pdf
          if-no-files-found: warn
